'use strict';
if (typeof module !== 'undefined' && module.exports) {
  const _c = require('./src/constants');
  Object.assign(global, _c);
  const { Size }               = require('./src/Size');               global.Size               = Size;
  const { Point }              = require('./src/Point');              global.Point              = Point;
  const { GameObject }         = require('./src/GameObject');         global.GameObject         = GameObject;
  const { InputHandler }       = require('./src/InputHandler');       global.InputHandler       = InputHandler;
  const { Enemy }              = require('./src/Enemy');              global.Enemy              = Enemy;
  const { EnemyWithAnimation } = require('./src/EnemyWithAnimation'); global.EnemyWithAnimation = EnemyWithAnimation;
  const { CatchableFish }      = require('./src/CatchableFish');      global.CatchableFish      = CatchableFish;
  const { InertObject }        = require('./src/InertObject');        global.InertObject        = InertObject;
  const { DiscardedBottle }    = require('./src/DiscardedBottle');    global.DiscardedBottle    = DiscardedBottle;
  const { RedApple }           = require('./src/RedApple');           global.RedApple           = RedApple;
  const { Wheel }              = require('./src/Wheel');              global.Wheel              = Wheel;
  const { Shoe }               = require('./src/Shoe');               global.Shoe               = Shoe;
  const { Octopus }            = require('./src/Octopus');            global.Octopus            = Octopus;
  const { Crab }               = require('./src/Crab');               global.Crab               = Crab;
  const { ButterflyFish }      = require('./src/ButterflyFish');      global.ButterflyFish      = ButterflyFish;
  const { LionFish }           = require('./src/LionFish');           global.LionFish           = LionFish;
  const { HammerHeadShark }   = require('./src/HammerHeadShark');   global.HammerHeadShark   = HammerHeadShark;
  const { SwordFish }         = require('./src/SwordFish');         global.SwordFish         = SwordFish;
  const { Tuna }               = require('./src/Tuna');               global.Tuna               = Tuna;
  const { ClownFish }          = require('./src/ClownFish');          global.ClownFish          = ClownFish;
  const { JellyFish }         = require('./src/JellyFish');         global.JellyFish         = JellyFish;
  const { PufferFish }        = require('./src/PufferFish');        global.PufferFish        = PufferFish;
  const { Shark }              = require('./src/Shark');              global.Shark              = Shark;
  const { ScoreSystem, SCORE_MAP } = require('./src/ScoreSystem');    global.ScoreSystem = ScoreSystem; global.SCORE_MAP = SCORE_MAP;
  const { ReelPowerBar }       = require('./src/ReelPowerBar');       global.ReelPowerBar       = ReelPowerBar;
  const { TimerSystem }        = require('./src/TimerSystem');        global.TimerSystem        = TimerSystem;
  const { AudioSystem }        = require('./src/AudioSystem');        global.AudioSystem        = AudioSystem;
  const { Hook }               = require('./src/Hook');               global.Hook               = Hook;
  const { Player }             = require('./src/Player');             global.Player             = Player;
  const { Bubble }             = require('./src/Bubble');             global.Bubble             = Bubble;
  module.exports = { Size, Point, GameObject, Enemy, EnemyWithAnimation, CatchableFish, InertObject, DiscardedBottle, RedApple, Wheel, Shoe, Octopus, Crab, ButterflyFish, LionFish, HammerHeadShark, SwordFish, Tuna, ClownFish, JellyFish, PufferFish, Shark, ScoreSystem, SCORE_MAP, ReelPowerBar, TimerSystem, AudioSystem, Hook, Player, Bubble };
}
