'use strict';
if (typeof module !== 'undefined' && module.exports) {
  const _c = require('./src/constants');
  Object.assign(global, _c);
  const { Size }               = require('./src/Size');               global.Size               = Size;
  const { Point }              = require('./src/Point');              global.Point              = Point;
  const { GameObject }         = require('./src/GameObject');         global.GameObject         = GameObject;
  const { InputSystem }        = require('./src/InputSystem');        global.InputSystem        = InputSystem;
  const { KeyboardInputSystem } = require('./src/KeyboardInputSystem'); global.KeyboardInputSystem = KeyboardInputSystem;
  const { TouchInputSystem }   = require('./src/TouchInputSystem');   global.TouchInputSystem   = TouchInputSystem;
  const { InputHandler }       = require('./src/InputHandler');       global.InputHandler       = InputHandler;
  const { MobileSystem }       = require('./src/MobileSystem');       global.MobileSystem       = MobileSystem;
  const { E2ETestHarness }     = require('./src/E2ETestHarness');     global.E2ETestHarness     = E2ETestHarness;
  const { Enemy }              = require('./src/Enemy');              global.Enemy              = Enemy;
  const { EnemyWithAnimation } = require('./src/EnemyWithAnimation'); global.EnemyWithAnimation = EnemyWithAnimation;
  const { CatchableFish }         = require('./src/CatchableFish');         global.CatchableFish         = CatchableFish;
  const { PremiumCatchableFish }  = require('./src/PremiumCatchableFish');  global.PremiumCatchableFish  = PremiumCatchableFish;
  const { InertObject }           = require('./src/InertObject');           global.InertObject           = InertObject;
  const { DiscardedBottle }    = require('./src/DiscardedBottle');    global.DiscardedBottle    = DiscardedBottle;
  const { RedApple }           = require('./src/RedApple');           global.RedApple           = RedApple;
  const { Wheel }              = require('./src/Wheel');              global.Wheel              = Wheel;
  const { Shoe }               = require('./src/Shoe');               global.Shoe               = Shoe;
  const { FishBone }           = require('./src/FishBone');           global.FishBone           = FishBone;
  const { Clock }              = require('./src/Clock');              global.Clock              = Clock;
  const { ChestWithJewels }   = require('./src/ChestWithJewels');   global.ChestWithJewels   = ChestWithJewels;
  const { Octopus }            = require('./src/Octopus');            global.Octopus            = Octopus;
  const { Crab }               = require('./src/Crab');               global.Crab               = Crab;
  const { Lobster }            = require('./src/Lobster');            global.Lobster            = Lobster;
  const { AnglerFlish }        = require('./src/AnglerFlish');        global.AnglerFlish        = AnglerFlish;
  const { ButterflyFish }      = require('./src/ButterflyFish');      global.ButterflyFish      = ButterflyFish;
  const { LionFish }           = require('./src/LionFish');           global.LionFish           = LionFish;
  const { HammerHeadShark }   = require('./src/HammerHeadShark');   global.HammerHeadShark   = HammerHeadShark;
  const { SwordFish }         = require('./src/SwordFish');         global.SwordFish         = SwordFish;
  const { Barracuda }         = require('./src/Barracuda');         global.Barracuda         = Barracuda;
  const { Tuna }               = require('./src/Tuna');               global.Tuna               = Tuna;
  const { ClownFish }          = require('./src/ClownFish');          global.ClownFish          = ClownFish;
  const { JellyFish }         = require('./src/JellyFish');         global.JellyFish         = JellyFish;
  const { PufferFish }        = require('./src/PufferFish');        global.PufferFish        = PufferFish;
  const { Shark }              = require('./src/Shark');              global.Shark              = Shark;
  const { ScoreSystem, SCORE_MAP } = require('./src/ScoreSystem');    global.ScoreSystem = ScoreSystem; global.SCORE_MAP = SCORE_MAP;
  const { ReelPowerBar }       = require('./src/ReelPowerBar');       global.ReelPowerBar       = ReelPowerBar;
  const { TimerSystem }        = require('./src/TimerSystem');        global.TimerSystem        = TimerSystem;
  const { AudioSystem }        = require('./src/AudioSystem');        global.AudioSystem        = AudioSystem;
  const { CaptureLaunchAnimation }   = require('./src/CaptureLaunchAnimation');   global.CaptureLaunchAnimation   = CaptureLaunchAnimation;
  const { CapturePoofAnimation }     = require('./src/CapturePoofAnimation');     global.CapturePoofAnimation     = CapturePoofAnimation;
  const { EscapeExplosionAnimation } = require('./src/EscapeExplosionAnimation'); global.EscapeExplosionAnimation = EscapeExplosionAnimation;
  const { Hook }               = require('./src/Hook');               global.Hook               = Hook;
  const { Player }             = require('./src/Player');             global.Player             = Player;
  const { Bubble }             = require('./src/Bubble');             global.Bubble             = Bubble;
  const { FishSpawner }        = require('./src/FishSpawner');        global.FishSpawner        = FishSpawner;
  module.exports = { Size, Point, GameObject, InputSystem, KeyboardInputSystem, TouchInputSystem, InputHandler, MobileSystem, E2ETestHarness, Enemy, EnemyWithAnimation, CatchableFish, PremiumCatchableFish, InertObject, DiscardedBottle, RedApple, Wheel, Shoe, FishBone, Clock, ChestWithJewels, Octopus, Crab, Lobster, AnglerFlish, ButterflyFish, LionFish, HammerHeadShark, SwordFish, Barracuda, Tuna, ClownFish, JellyFish, PufferFish, Shark, ScoreSystem, SCORE_MAP, ReelPowerBar, TimerSystem, AudioSystem, CaptureLaunchAnimation, CapturePoofAnimation, EscapeExplosionAnimation, Hook, Player, Bubble, FishSpawner };
}
